version: '3'

services:


  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www
    env_file:
      - .env
    networks:
      - dockernet
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dockernet
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp:/var/www
    networks:
      - dockernet
    restart: always

volumes:
  db:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/mariadb
      o: bind
  wp:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/wordpress
      o: bind

networks:
  dockernet:
    driver: bridge
