# Base image
FROM mariadb:10.6.4

# Set environment variables for data base
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wordpress
ENV MYSQL_PASSWORD=password

# Open ports for remote access
EXPOSE 3306

# # Start mariadb service
# CMD ["mysqld", "--user=mysql"]
